# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-18 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='purchase_price',
        ),
        migrations.AddField(
            model_name='stock',
            name='current_stock_price',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='initial_stock_price',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=10),
            preserve_default=False,
        ),
    ]
